### ISSUE TITLE
可以整个c#版的吗

### ISSUE THREAD

**Issue by woaidianqian** [BiLiangLtd/WordSimilarity#1]

**Comment by GengYuIsland** [comment]
不可以，你想太多了

**Comment by yaleimeng** [comment]
读懂代码自己用熟悉的语言改写，这才是开源的价值所在。——不只是代码的搬运，而是知识的传递
我的项目[Final_word_Similarity ](https://github.com/yaleimeng/Final_word_Similarity) 也可以了解一下。
