### ISSUE TITLE
__init__.py建议修改，打开文件时要用UTF-8格式打开才不会报错

### ISSUE THREAD

**Issue by woaidianqian** [BiLiangLtd/WordSimilarity#2]
def _load_cilin(self, file_path):

        '''
        加载词林数据。
        :return:
        '''

        file_obj = open(file_path, 'r',  encoding='UTF-8')
        line_num = 0
        while True:
            line_num += 1
            line = file_obj.readline()

**Comment by yaleimeng** [comment]
我的项目[Final_word_Similarity ](https://github.com/yaleimeng/Final_word_Similarity) 在计算效果上更优，使用也不复杂。您也可以了解一下。
